config/routes.rb
Dinnertyme::Application.routes.draw do

  get "kitchens/index"

  get "kitchens/show"

  get "kitchens/new"

  post "kitchens/create"

  get "kitchens/edit"

  get "kitchens/update"

  get "kitchens/destroy"

  resources :recipes
  resources :ingredients
  resources :kitchens

  root :to => 'home#index'

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  attr_accessible :name, :unit, :amount

  has_and_belongs_to_many :recipes

end

app/models/kitchen.rb
class Kitchen < ActiveRecord::Base
  attr_accessible :name

  has_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :photo, :rating, :serves, :steps, :ingredient_ids, :remote_photo_url, :kitchen_id

  has_and_belongs_to_many :ingredients
  belongs_to :kitchen

  mount_uploader :photo, RecipepicUploader


  def self.search(search)
    where('name ILIKE ?', "%#{search}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	  offset = rand(Recipe.count).ceil
	  @recipes = Recipe.find(:all, :limit => 3, :order => "created_at DESC")
	end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end

  def show
    @ingredient = Ingredient.find(params[:id])
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(params[:ingredient])
    if @ingredient.save
      redirect_to ingredients_path, :notice => "Ingredient successfully added."
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end

  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update_attributes(params[:ingredient])
      redirect_to ingredients_path
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    redirect_to ingredients_path, :notice => "Ingredient has been deleted."
  end
end

app/controllers/kitchens_controller.rb
class KitchensController < ApplicationController
  def index
    @kitchens = Kitchen.all
  end

  def show
    @kitchen = Kitchen.find(params[:id])
  end

  def new
    @kitchen = Kitchen.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @kitchens = []
    params[:kitchen].each do |kitchen|
      new_kitchen = Kitchen.new(kitchen)
      if new_kitchen.save
        @kitchens << new_kitchen
      end
    end
    respond_to do |format|
      format.js
    end
  end


  def edit
    @kitchen = Kitchen.find(params[:id])
  end

  def update
    @kitchen = Kitchen.find(params[:id])
    if @kitchen.update_attributes(params[:kitchen])
      redirect_to kitchens_path, :notice => "#{@kitchen.name}'s kitchen has been updated"
    else
      render 'edit'
    end
  end

  def destroy
    @kitchen = Kitchen.find(params[:id])
    @kitchen.destroy
    redirect_to kitchens_path, :notice => "Kitchen successfully deleted."
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    if params[:search]
      @recipes = Recipe.search(params[:search])
    else
      @recipes = Recipe.all
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(params[:recipe])
    if @recipe.save
      redirect_to recipes_path, :notice => "Recipe successfully created."
    else
      render 'new'
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if @recipe.update_attributes(params[:recipe])
      redirect_to recipes_path, :notice => "Recipe successfully updated."
    else
      render 'edit'
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    flash[:notice] = "Recipe deleted."
    redirect_to recipes_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def full_ingredient_name(ingredient)
  	"#{ingredient.amount} #{ingredient.unit} of #{ingredient.name}"
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/kitchens_helper.rb
module KitchensHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/home/index.html.erb
    <div class="hero-unit">
    <h1>Welcome to DinnerTyme!</h1>
    <p>Browse through different kitchens, each with their own unique themes and recipes. Or create your own!</p>
    <p>
    <a class="btn btn-primary btn-large" href="<%= kitchens_path %>">
    Browse Kitchens!
    </a>
    </p>
    </div>

    <h2>Recently added recipes:</h2>
    <% @recipes.each do |recipe| %>
    <div class="recipepic">
		<%= recipe.name %> by <%= recipe.kitchen ? link_to(recipe.kitchen.name, kitchen_path(recipe.kitchen)) : link_to("No kitchen", edit_recipe_path(recipe)) %><br>
		<%= link_to (recipe.photo.thumb.url ? image_tag(recipe.photo.thumb.url) : image_tag('questionmark.png', :height => "300", :width => "300")), recipe_path(recipe) %>
	</div>
<% end %>

app/views/ingredients/_form.html.erb
<%= form_for(@ingredient) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :amount %>
<%= f.text_field :amount %>

<%= f.label :unit %>
<%= f.text_field :unit %>

<br>
<%= f.submit %>

<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient:</h1>
<p><%= link_to "Back to Ingredients", ingredients_path %></p>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<%= link_to "Add a new ingredient", new_ingredient_path %>
<br>
<br>
<% @ingredients.each do |ingredient| %>
<div class="ingredientbox span4 offset1">
	<%= ingredient.name %> (<%= ingredient.amount %> <%= ingredient.unit %>)
	<%= link_to "Edit", edit_ingredient_path(ingredient) %>
	<%= link_to "Remove", ingredient_path(ingredient), :method => :delete, :confirm => "Are you sure?" %>
</div>
<% end %>

app/views/ingredients/new.html.erb
<h1>Ingredients</h1>
<p><%= link_to "Back to Ingredients", ingredients_path %></p>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<h1>Ingredients#show</h1>
<p>Find me in app/views/ingredients/show.html.erb</p>

app/views/kitchens/_box.html.erb
		<%= label_tag "Name" %>
		<%= text_field_tag "kitchen[][name]" %>

app/views/kitchens/_form.html.erb
<%= form_for(@kitchen) do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<br>
<%= f.submit %>

<% end %>

app/views/kitchens/_kitchen.html.erb
<div class="kitchenbox span3">
	<h3><%= link_to kitchen.name, kitchen_path(kitchen) %></h3>
	<%= link_to "Edit", edit_kitchen_path(kitchen) %> |
	<%= link_to "Delete", kitchen_path(kitchen), :method => :delete, :confirm => "Are you sure?" %> 
</div>

app/views/kitchens/create.js.erb
$(".createkitchendiv").html("");
$(".createkitchendiv").append("<%= j link_to 'Create new kitchen', new_kitchen_path, :id => 'createkitchenlink' %>");
$(".kitchenholder").append("<%= j render :partial => 'kitchens/kitchen', :collection => @kitchens, :as => :kitchen %>");

app/views/kitchens/edit.html.erb
<h1>Edit Kitchen</h1>
<p><%= link_to "Back to Kitchens", kitchens_path %></p>

<%= render 'form' %>

app/views/kitchens/index.html.erb
<div class="span12">
	<h1>Kitchens</h1>
	
	<div class="createkitchendiv">
		<%= link_to "Create new kitchen", new_kitchen_path, :id => "createkitchenlink" %>

	
			<%= form_tag "/kitchens/create", :method => :post, :remote => true do %>

			<div class="blahblah">
			<%= render :partial => "box" %>

			</div>
			<%= submit_tag "Submit" %>

		<% end %>
		</div>


<div class="kitchenholder offset1">
<%= render :partial => 'kitchen', :collection => @kitchens, :as => :kitchen %>
</div>

</div>

app/views/kitchens/new.js.erb
$(".blahblah").append(<%= render 'box' %>)

app/views/kitchens/show.html.erb
<div>
<h1><%= @kitchen.name %></h1>
<%= link_to "View all Kitchens", kitchens_path %>
</div>

<%= render :partial => 'shared/recipe', :collection => @kitchen.recipes, :as => :recipe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dinnertyme</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "/favicon.ico?1" %>
</head>
<body>
  <div class="container">
	<div class="navbar">
    	<div class="navbar-inner">
    		<a class="brand" href="<%= root_path %>">DinnerTyme</a>
    		<ul class="nav">
	    		<li><%= link_to 'Kitchens', kitchens_path %></li>
	    		<li><%= link_to 'Recipes', recipes_path %></li>
	    		<li><%= link_to 'Ingredients', ingredients_path %></li>
    		</ul>
   		</div>
    </div>

    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>



	<%= yield %>
  <div class="container">
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(@recipe, :html => { :multipart => true }) do |f| %>

<%= f.select :kitchen_id, Kitchen.all.map { |k| [k.name, k.id] }, :include_blank => true %>

 
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :steps %>
<%= f.text_area :steps %>

<%= f.label :photo %>
<%= f.file_field :photo %>
<br>
OR directly paste image link:
<%= f.text_field :remote_photo_url %>

<%= f.label :serves %>
<%= f.text_field :serves %>

<%= f.label :rating %>
<%= f.select :rating, (1..5).to_a %>

<br>
Ingredients:
<% Ingredient.all.each do |ingredient| %>
<div>
	<span><%= "#{ingredient.name}: #{ingredient.amount} #{ingredient.unit}"%></span>
	<%= check_box_tag 'recipe[ingredient_ids][]', ingredient.id, @recipe.ingredients.include?(ingredient) %>
</div>
<% end %>
<br>
<%= f.submit %>

<% end %>

app/views/recipes/edit.html.erb
<h1>Recipes#edit</h1>
<p>Find me in app/views/recipes/edit.html.erb</p>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class="recipesheading">
	<h1>Recipes</h1>
	<%= link_to "Add recipe", new_recipe_path %>

	<%= form_tag recipes_path, :method => "get" do %>
		<%= label_tag(:search, "Search recipe name") %>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	<% end %>
</div>
<% @recipes.each do |recipe| %>
<%# binding.pry %>
<div class="recipepic">
<%= link_to recipe.name, recipe_path(recipe) %> by <%= recipe.kitchen ? link_to(recipe.kitchen.name, kitchen_path(recipe.kitchen)) : link_to("(Kitchen not specified)", edit_recipe_path(recipe)) %><br>
<%= link_to (recipe.photo.thumb.url ? image_tag(recipe.photo.thumb.url) : image_tag('questionmark.png', :height => "300", :width => "300")), recipe_path(recipe) %>
</div>
<% end %>

app/views/recipes/new.html.erb
<h1>Add a New Recipe:</h1>
<p><%= link_to "Back to Recipes", recipes_path %></p>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class="recipeheading">
<h1><%= @recipe.name %></h1>
<%= link_to "Edit recipe", edit_recipe_path(@recipe) %> |
<%= link_to "Delete recipe", recipe_path(@recipe), :method => :delete, :confirm => "Are you sure?" %>
</div>

<div class="container-fluid">
	<div class="row-fluid">
	<div class="span6">
		<%= image_tag(@recipe.photo.url ? @recipe.photo.url : "questionmark.png", :class => "recipepic") %>
	</div>

<div class="span5">
<div>
	<h3>By <%= @recipe.kitchen ? (link_to @recipe.kitchen.name, kitchen_path(@recipe.kitchen)) : (link_to "Not specified", edit_recipe_path(@recipe)) %></h3>
</div>

<div>
	<h3>Ingredients:</h3>
	<% @recipe.ingredients.each do |ingredient| %>
	<p><%= full_ingredient_name(ingredient) %>
	<% end %>
</div>

<div>
	<h2>Directions:</h2>
	<%= @recipe.steps %>
</div>
<div>
	<h4>Serves: <b><%= pluralize(@recipe.serves, "person") %></b>
</div>

<div>
	<h4>Rating:
	<% if @recipe.rating %>
	<% @recipe.rating.times do |i| %>
		<%= image_tag("star.jpg", :size => "50x50") %>
	<% end %>
	<% else %>
		<%= link_to "No rating", edit_recipe_path(@recipe) %>
	<% end %>
	</h4>
</div>
</div>

</div>
</div>

app/views/shared/_recipe.html.erb
<div class="recipepic">
<%= link_to recipe.name, recipe_path(recipe) %> by <%= recipe.kitchen ? link_to(recipe.kitchen.name, kitchen_path(recipe.kitchen)) : link_to("Kitchen not specified", edit_recipe_path(recipe)) %><br>
<%= link_to (recipe.photo.thumb.url ? image_tag(recipe.photo.thumb.url) : image_tag('questionmark.png', :height => "300", :width => "300")), recipe_path(recipe) %>
</div>